### PR TITLE
Add Home URL and Source Code URL

### PR DESCRIPTION
**Pull request by KyleTryon**
Display a link to your home page and the orb source natively in the Orb registry as a clickable link.

### CODE REVIEW

**Comment by PhilipAbed** [comment]
Thanks, It's Done.

**Comment by KyleTryon** [comment]
@PhilipAbed Merged in a separate branch? I do not see the change: https://github.com/whitesource/wss-vc-circleci-integration/blob/master/config.yaml#L2

**Comment by PhilipAbed** [comment]
the config in github is old ,

i changed online this web: https://circleci.com/orbs/registry/orb/whitesource/whitesource-scan
i created pull request to change it here too

**Review by PhilipAbed — APPROVED** [review]

**Review by annarozin — COMMENTED** [review]
Please contact WhiteSource support

**Comment by ryanwohara** [comment]
@annarozin Either accept or close the PR. Why would he contact your support? Lmao.

**Pull request closed without merging**
